# Generated by Django 5.1.7 on 2025-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_info_add_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teachers_info_add_teacher_honorifics', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_f_name', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_username', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_l_name', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_email', models.EmailField(max_length=150)),
                ('Teachers_info_add_teacher_phoneno', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_password', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_designation', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_department', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_gender', models.CharField(max_length=150)),
                ('Teachers_info_add_teacher_joindate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
