# Generated by Django 5.1.7 on 2025-04-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0002_teachers_info_add_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_info_add_teacher',
            name='Teachers_info_add_teacher_gender',
        ),
    ]
