# Generated by Django 5.1.7 on 2025-04-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0003_remove_teachers_info_add_teacher_teachers_info_add_teacher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_info_add_teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teachers_info_add_teacher',
            name='Teachers_info_add_teacher_serial_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
