# Generated by Django 5.1.7 on 2025-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0005_teacherauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherauth',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
