# Generated by Django 5.1.7 on 2025-04-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0006_teacherauth_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherauth',
            name='is_superuser',
        ),
    ]
