# Generated by Django 5.1.7 on 2025-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0007_remove_teacherauth_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_info_add_teacher',
            name='Teachers_info_add_teacher_serial_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
