# Generated by Django 5.1.7 on 2025-04-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0008_alter_teachers_info_add_teacher_teachers_info_add_teacher_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherauth',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherauth',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
