# Generated by Django 5.1.7 on 2025-04-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0009_teacherauth_is_staff_teacherauth_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info_add_student',
            fields=[
                ('Student_info_add_student_serial_number', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Student_info_add_student_f_name', models.CharField(max_length=150)),
                ('Student_info_add_student_l_name', models.CharField(max_length=150)),
                ('Student_info_add_student_father_name', models.CharField(max_length=150)),
                ('Student_info_add_student_mother_name', models.CharField(max_length=150)),
                ('Student_info_add_student_college_ro', models.CharField(max_length=150)),
                ('Student_info_add_student_gender', models.CharField(max_length=150)),
                ('Student_info_add_student_email', models.EmailField(max_length=150)),
                ('Student_info_add_student_username', models.CharField(max_length=150)),
                ('Student_info_add_student_DoB', models.DateField()),
                ('Student_info_add_student_phoneno', models.CharField(max_length=150)),
                ('Student_info_add_student_adress', models.CharField(max_length=400)),
                ('Student_info_add_student_categori', models.CharField(max_length=150)),
                ('Student_info_add_student_Disable_status', models.CharField(max_length=150)),
                ('Student_info_add_student_password', models.CharField(max_length=150)),
                ('Student_info_add_student_department', models.CharField(max_length=150)),
                ('Student_info_add_student_branch', models.CharField(max_length=150)),
                ('Student_info_add_student_photo', models.ImageField(max_length=300, upload_to='student_reg_pics')),
                ('Student_info_add_student_sign', models.ImageField(max_length=300, upload_to='student_reg_sign')),
                ('Student_info_add_student_idproof', models.FileField(max_length=300, upload_to='student_reg_document_idproof')),
                ('Student_info_add_student_joindate', models.DateTimeField(auto_now_add=True)),
                ('Student_info_add_student_exam_rollnumber', models.CharField(default=None, editable=False, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_info', to='ru_exam_admin.student_info_add_student')),
            ],
        ),
    ]
