# Generated by Django 5.1.7 on 2025-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0010_student_info_add_student_studentauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentauth',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
