# Generated by Django 5.1.7 on 2025-04-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0011_alter_studentauth_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_exam_rollnumber',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
