# Generated by Django 5.1.7 on 2025-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0012_alter_student_info_add_student_student_info_add_student_exam_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_serial_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
