# Generated by Django 5.1.7 on 2025-04-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0014_alter_student_info_add_student_student_info_add_student_idproof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_idproof',
            field=models.FileField(max_length=300, upload_to='student_reg_document_idproof'),
        ),
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_photo',
            field=models.ImageField(max_length=300, upload_to='student_reg_pics'),
        ),
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_sign',
            field=models.ImageField(max_length=300, upload_to='student_reg_sign'),
        ),
    ]
