# Generated by Django 5.1.7 on 2025-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0016_alter_student_info_add_student_student_info_add_student_idproof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
