# Generated by Django 5.1.7 on 2025-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0017_alter_student_info_add_student_student_info_add_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_email',
            field=models.EmailField(max_length=150),
        ),
    ]
