# Generated by Django 5.1.7 on 2025-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_exam_admin', '0018_alter_student_info_add_student_student_info_add_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info_add_student',
            name='Student_info_add_student_exam_rollnumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
